"""add transmission_type

Revision ID: f27db1e929a1
Revises: eb547856e1a6
Create Date: 2026-03-27 22:21:19.432708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27db1e929a1'
down_revision: Union[str, Sequence[str], None] = 'eb547856e1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cars',
        sa.Column('transmission_type', sa.String(length=20), nullable=False, server_default='manual')
    )
    op.drop_column('cars', 'transmission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('transmission', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('cars', 'transmission_type')
    # ### end Alembic commands ###
